version: '3.9'

services:
  web:
    image: youtube_sieve
    build: .
    env_file:
      - .env
    command: gunicorn youtube_script_sieve.wsgi:application --bind 0.0.0.0:8000 --limit-request-line 0 --access-logfile gunicorn.log --workers=4
    expose:
      - "8000"

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    restart: "unless-stopped"
    depends_on:
      web:
        condition: service_started
